### ISSUE TITLE
Custom module error

### ISSUE THREAD

**Issue by Running-z** [simonfqy/PADME#3]
Hello, I watched your research, I tried to run your example, and when I ran the file drive. sh, I got a custom module error:
```
Traceback (most recent call last):
  File "driver.py", line 20, in <module>
    import dcCustom
  File "/project/git/PADME/dcCustom/__init__.py", line 14, in <module>
    import dcCustom.metrics
  File "/project/git/PADME/dcCustom/metrics/__init__.py", line 11, in <module>
    from dcCustom.metrics.cindex_measure import cindex
  File "/project/git/PADME/dcCustom/metrics/cindex_measure.py", line 9, in <module>
    from dcCustom.metrics import swapped
ImportError: cannot import name 'swapped'
```
I do see that there is no swapped in the dcCustom.metrics file that you define. Can you give me some guidance?

**Comment by simonfqy** [comment]
Thanks for your interest. The module `swapped` corresponds to a `.so` file generated by running `metrics/setup.py`, which I have already included in the repository. You can also generate it by yourself. Please refer to the explanation on [this page](https://github.com/simonfqy/PADME/tree/master/dcCustom/metrics) for details.

**Comment by Running-z** [comment]
@simonfqy 
ok,ok, Thank you

**Comment by Running-z** [comment]
@simonfqy 
Okay, thank you. I solved this error according to what you said, but it seems that you are missing two copies of data. Under the two folders of metz_data and KIBA_data, it seems that you are missing the prot_desc.csv data file. When I run the drive.sh script, I got an error message telling me that there is no pro_desc.csv file.

**Comment by simonfqy** [comment]
Hi previously I intentionally did so to prevent other people from running my program and claim the originality before I do. Now it is fine and I just uploaded the files. Does it work correctly now?
For the `full_toxcast` folder, you need to set it as the working directory and run `python preprocess.py` to generate `restructured.csv` file. Or you can ask me to send it to you. 
For `NCI60_data` folder, there are many large files which cannot be put in GitHub. If you want them please request it from me through email.

**Comment by Running-z** [comment]
@simonfqy 
Okay, thank you very much. Can you give me the files that can't be uploaded to github? My email is 101744010@qq.com, and can you give me a description of the data set you use? For example, the description of Davis data, or you get the original parper or link of the data, I don't understand the actual meaning of the data, and that's it. I am puzzled. Thank you very much.

**Comment by simonfqy** [comment]
Hi @Running-z , I think it would not be helpful to send you the large files in `NCI60_data` since it is much more complicated and not that similar to the other 4 datasets, namely `Davis`, `Metz`, `KIBA` and `ToxCast`. 

You can refer to the [SimBoost paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5395521/) by Tong et al., 2017, to get some understanding of Davis, Metz and KIBA datasets. If you are still puzzled you can refer to the reference section of the SimBoost paper to go to those papers that first introduced those datasets to the community.

**Comment by Running-z** [comment]
@simonfqy 
Ok, thank you very much, can you ask a question? There is a "davis" attribute in the restructured.csv file under the davis_data folder. Where does the value below this attribute come from, what does it mean?? Sorry, I know how your data is handled, sorry.
![default](https://user-images.githubusercontent.com/38971699/44825508-76bed300-ac3d-11e8-8d45-2492432c7879.png)

**Comment by simonfqy** [comment]
@Running-z I think my naming is a bit problematic. It means the Davis data interaction values (K_d, kinase dissociation constant). You can refer to the SimBoost paper, whose link I have already given in a previous comment. It is obtained from `davis_data/Bio_results.csv`, I collected the drug-target pairs from `Bio_results.csv` and restructured them into `restructured.csv`. The task is done in `davis_data/preprocess.py`, but currently this `.py` file is not generating the `restructured.csv`: it is generating the binarized values instead. You can modify it as you wish, or directly use my `restructured.csv` file.

**Comment by simonfqy** [comment]
Hi @Running-z if you are asking a question unrelated to the initial topic of a thread, please open a new thread instead of continuing the existing thread. It will help future readers to find your problems and my answers. Thanks.

**Comment by Running-z** [comment]
@simonfqy 
OK, OK, thank you. I will do what you ask.

**Comment by simonfqy** [comment]
The problem seems to be resolved. Feel free to reopen it if it still bothers you.
